/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.41.0.0
 *
 * Project: 'Pj1-BlinkLed' 
 * Target:  'Target_1' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32l4xx.h"

/* Keil::Device:Startup@1.3.2 */
#define RTE_DEVICE_STARTUP_STM32L4XX    /* Device Startup for STM32L4 */


#endif /* RTE_COMPONENTS_H */
